### ISSUE TITLE
P2418D HDMI 连接开启不了吗？

### ISSUE THREAD

**Issue by zealforbeing** [wacky6/newbie#1]
同P2418D，HDMI连接尝试开启hidpi，但是都失败了，黑苹果下只有1080p非hidpi，mbp有2k非hidpi

**Comment by wacky6** [comment]
本来也没说p2418d可以hdmi。另外，黑苹果不在考虑范围

**Comment by zealforbeing** [comment]
> 本来也没说p2418d可以hdmi。另外，黑苹果不在考虑范围

感谢回复
